USE tienda;
SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT * FROM producto;
SELECT nombre, concat(precio, "€"), concat(FORMAT(precio * 1.05, 2), " USD") FROM producto;
SELECT nombre, concat(precio, "€") AS euros, concat(FORMAT(precio * 1.05, 2), "USD") AS dolars FROM producto;
SELECT UCASE(nombre) AS nombre, precio FROM producto;
SELECT LCASE(nombre) AS nombre, precio FROM producto;
SELECT nombre, UCASE(LEFT(nombre, 2)) FROM fabricante;
SELECT nombre, ROUND(precio) AS precio FROM producto;
SELECT nombre, TRUNCATE(precio, 0) AS precio FROM producto;
SELECT codigo_fabricante FROM producto;
SELECT DISTINCT codigo_fabricante FROM producto;
SELECT nombre FROM fabricante ORDER BY nombre;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT nombre, precio FROM producto ORDER BY nombre, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 2 OFFSET 3;
SELECT nombre, precio FROM producto ORDER BY precio LIMIT 1;
SELECT nombre, precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT nombre FROM producto WHERE codigo_fabricante = 2;
SELECT producto.nombre, producto.precio , fabricante.nombre AS fabricante FROM producto INNER JOIN fabricante ON fabricante.codigo = producto.codigo_fabricante;
SELECT producto.nombre, producto.precio , fabricante.nombre AS fabricante FROM producto INNER JOIN fabricante ON fabricante.codigo = producto.codigo_fabricante ORDER BY fabricante.nombre;
SELECT producto.codigo, producto.nombre, fabricante.codigo AS codigo_fabricante , fabricante.nombre AS fabricante FROM producto INNER JOIN fabricante ON fabricante.codigo = producto.codigo_fabricante;
SELECT producto.nombre, producto.precio , fabricante.nombre AS fabricante FROM producto INNER JOIN fabricante ON fabricante.codigo = producto.codigo_fabricante ORDER BY producto.precio LIMIT 1;
SELECT producto.nombre, producto.precio , fabricante.nombre AS fabricante FROM producto INNER JOIN fabricante ON fabricante.codigo = producto.codigo_fabricante ORDER BY producto.precio DESC LIMIT 1;
SELECT producto.nombre, producto.precio , fabricante.nombre AS fabricante FROM producto INNER JOIN fabricante ON fabricante.codigo = producto.codigo_fabricante WHERE fabricante.nombre = "Lenovo";
SELECT producto.nombre, producto.precio , fabricante.nombre AS fabricante FROM producto INNER JOIN fabricante ON fabricante.codigo = producto.codigo_fabricante WHERE fabricante.nombre = "Crucial" AND producto.precio > 200;
SELECT producto.nombre, producto.precio , fabricante.nombre AS fabricante FROM producto INNER JOIN fabricante ON fabricante.codigo = producto.codigo_fabricante WHERE fabricante.nombre = "Asus" OR fabricante.nombre = "Hewlett-Packard" OR fabricante.nombre = "Seagate";
SELECT producto.nombre, producto.precio , fabricante.nombre AS fabricante FROM producto INNER JOIN fabricante ON fabricante.codigo = producto.codigo_fabricante WHERE fabricante.nombre IN ("Asus", "Hewlett-Packard", "Seagate");
SELECT producto.nombre, producto.precio , fabricante.nombre AS fabricante FROM producto INNER JOIN fabricante ON fabricante.codigo = producto.codigo_fabricante WHERE RIGHT(fabricante.nombre, 1) = "e";
SELECT producto.nombre, producto.precio , fabricante.nombre AS fabricante FROM producto INNER JOIN fabricante ON fabricante.codigo = producto.codigo_fabricante WHERE fabricante.nombre LIKE "%w%";
SELECT producto.nombre, producto.precio , fabricante.nombre AS fabricante FROM producto INNER JOIN fabricante ON fabricante.codigo = producto.codigo_fabricante WHERE producto.precio > 180 ORDER BY producto.precio DESC, producto.nombre;
SELECT * FROM fabricante WHERE EXISTS(SELECT * FROM producto WHERE fabricante.codigo = producto.codigo_fabricante);
SELECT fabricante.nombre, producto.nombre AS producto FROM fabricante LEFT JOIN producto ON producto.codigo_fabricante = fabricante.codigo;
SELECT * FROM fabricante WHERE NOT EXISTS(SELECT * FROM producto WHERE fabricante.codigo = producto.codigo_fabricante);
SELECT nombre, precio FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE fabricante.nombre = "Lenovo"); 
SELECT nombre, precio FROM producto WHERE precio = (SELECT MAX(precio) FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE fabricante.nombre = "Lenovo"));
SELECT nombre, precio FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE fabricante.nombre = "Lenovo") ORDER BY precio DESC LIMIT 1; 
SELECT nombre, precio FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE fabricante.nombre = "Hewlett-Packard") ORDER BY precio LIMIT 1; 
SELECT nombre, precio FROM producto WHERE precio >= (SELECT MAX(precio) FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE fabricante.nombre = "Lenovo"));